[package]
name = "calculator-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "calculator_client"
test = false
bench = false

[[bin]]
name = "calculator_server"
test = false
bench = false
