[package]
name = "uppercaser"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"

[[bin]]
name = "client"
test = false
bench = false

[[bin]]
name = "server"
test = false
bench = false
