[package]
name = "uppercaser"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"

[[bin]]
name = "uppercaser-client"
path = "src/client.rs"
test = false
bench = false

[[bin]]
name = "uppercaser-server"
path = "src/server.rs"
test = false
bench = false
